os:
  - linux
sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
  - npm run validateJsons
notifications:
  email: false